services:
  booking-reference:
    build:
      context: ./booking_reference
      dockerfile: Dockerfile
    container_name: booking_reference_service
    ports:
      - "8082:8082"

  train-data:
    build:
      context: ./train_data_service
      dockerfile: Dockerfile
    container_name: train_data_service
    ports:
      - "8081:8081"
    depends_on:
      - booking-reference