spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      indent-output: true
    deserialization:
      fail-on-unknown-properties: false
  docker:
    compose:
      enabled: false

booking-reference-service:
  url: ${BOOKING_REFERENCE_HOST_URL}:${BOOKING_REFERENCE_PORT}

train-data-service:
  url: ${TRAIN_DATA_SERVICE_HOST_URL}:${TRAIN_DATA_SERVICE_PORT}