spring:
  main:
    banner-mode: off
  jackson:
    default-property-inclusion: non_null
    serialization:
      indent-output: true
    deserialization:
      fail-on-unknown-properties: false
logging:
  level:
    org.springframework: ERROR

train-data-service:
  url: http://127.0.0.1
  port: 8081
booking-reference-service:
  url: http://127.0.0.1
  port: 8082
